export default function() {
  return {
    chatList: [
      {
        id: 1,
        nickname: 'peter',
        profile_photo: 'https://randomuser.me/api/portraits/men/89.jpg',
        like: 2300,
        photo: 'http://corporate.mystays.com/k/column/images/mv_009.jpg',
        name: '교토로 3박4일 가실분!',
        city_name: 'Kyoto',
        start_at: '2017-10-14',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ut neque impedit? Pariatur natus delectus aspernatur mollitia soluta architecto tenetur. Cumque omnis doloribus delectus? Exercitationem sed quasi nihil magni odit.',
        current_users: 3,
      },
      {
        id: 2,
        nickname: 'seult',
        profile_photo: 'https://randomuser.me/api/portraits/women/64.jpg',
        like: 2300,
        photo: 'http://tourimage.interpark.com/product/tour/00161/A10/500/A1016460_7_480.jpg',
        name: '방콕으로 3박4일 가실분!',
        city_name: 'Bangkok',
        start_at: '2017-10-17',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ut neque impedit? Pariatur natus delectus aspernatur mollitia soluta architecto tenetur. Cumque omnis doloribus delectus? Exercitationem sed quasi nihil magni odit.',
        current_users: 4,
      },
      {
        id: 3,
        nickname: 'younghea',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '로마로 3박4일 가실분!',
        city_name: 'Rome',
        start_at: '2017-11-01',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 4,
      },
      {
        id: 4,
        nickname: 'younghea4',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '도쿄로 3박4일 가실분!',
        city_name: 'Tokyo',
        start_at: '2017-12-12',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 3,
      },
      {
        id: 5,
        nickname: 'younghea5',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '바르셀로나로 1박2일 가실분!',
        city_name: 'Barcelona',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 2,
      },
      {
        id: 6,
        nickname: 'younghea6',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '세부로 3박4일 가실분!',
        city_name: 'Cebu',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 1,
      },
      {
        id: 7,
        nickname: 'younghea7',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '도쿄로 3박4일 가실분!',
        city_name: 'Tokyo',
        start_at: '2017-12-12',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 3,
      },
      {
        id: 8,
        nickname: 'younghea8',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '바르셀로나로 1박2일 가실분!',
        city_name: 'Barcelona',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 2,
      },
      {
        id: 9,
        nickname: 'younghea9',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '세부로 3박4일 가실분!',
        city_name: 'Cebu',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 1,
      },
      {
        id: 10,
        nickname: 'younghea10',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '도쿄로 3박4일 가실분!',
        city_name: 'Tokyo',
        start_at: '2017-12-12',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 3,
      },
      {
        id: 11,
        nickname: 'younghea11',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '바르셀로나로 1박2일 가실분!',
        city_name: 'Barcelona',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 2,
      },
      {
        id: 12,
        nickname: 'younghea12',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '세부로 3박4일 가실분!',
        city_name: 'Cebu',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 1,
      },
      {
        id: 13,
        nickname: 'younghea13',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '세부로 3박4일 가실분!',
        city_name: 'Cebu',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 1,
      },
      {
        id: 14,
        nickname: 'younghea14',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 2300,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '도쿄로 3박4일 가실분!',
        city_name: 'Tokyo',
        start_at: '2017-12-12',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 3,
      },
      {
        id: 15,
        nickname: 'younghea15',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 10,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '바르셀로나로 1박2일 가실분!',
        city_name: 'Barcelona',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 2,
      },
      {
        id: 16,
        nickname: 'younghea16',
        profile_photo: 'https://randomuser.me/api/portraits/men/79.jpg',
        like: 5,
        photo: 'http://www.yeeum.com/wp-content/uploads/2015/03/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4-%EB%A9%94%EC%9D%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg',
        name: '세부로 3박4일 가실분!',
        city_name: 'Cebu',
        start_at: '2017-11-20',
        description: '군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다. 군사재판을 관할하기 위하여 특별법원으로서 군사법원을 둘 수 있다. 외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
        current_users: 1,
      },
    ]
  }
}